# =============================================================================
# Harness Input Set - Development Environment
# =============================================================================

inputSet:
  name: Dev Environment
  identifier: dev_environment
  orgIdentifier: ${HARNESS_ORG_ID}
  projectIdentifier: ${HARNESS_PROJECT_ID}
  pipeline:
    identifier: etl_pipeline_deployment
    variables:
      - name: environment
        type: String
        value: dev
      - name: aws_region
        type: String
        value: us-east-1
      - name: auto_approve
        type: String
        value: "true"  # Auto-approve for dev
